### ISSUE TITLE
Authorizing link results in error 400

### ISSUE THREAD

**Issue by Torwak** [l3uddz/gdsa_maker#3]
I used this a few months ago and it worked great. I tried it out again today but I got this error when authorizing the app 
<img width="699" alt="Screenshot 2019-10-26 at 0 50 45" src="https://user-images.githubusercontent.com/17184031/67606862-58922b80-f78b-11e9-8dd5-d603990e21ee.png">

**Comment by desimaniac** [comment]
No Readme yet but ill write them out here:

1. Install python3 and requirements.txt
1. Run `./sa-maker.py` to generate a basic `config.json` file.
1. Create a project on Google Console.
1. Enable the following APIs:
   1. Google Drive API
   1. Identity and Access Management (IAM) API
   1. Admin SDK
1. Create an OAuth Client ID
1. Add OAuth Client ID, OAuth Client Secret, and Project ID into your `config.json` file.
1. Run `./sa-maker.py authorize` to authorize and build your `token.json` file.
1. Done

**Comment by m4nnerheim** [comment]
Yeah thanks, I missed running it once first.
